"""add mfa columns

Revision ID: 07c0be127c34
Revises: dee28e8b3cc1
Create Date: 2026-06-09 11:52:31.621658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07c0be127c34'
down_revision: Union[str, Sequence[str], None] = 'dee28e8b3cc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totp_secret', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_mfa_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_mfa_enabled')
    op.drop_column('users', 'totp_secret')
    # ### end Alembic commands ###
