"""bind token to device info

Revision ID: ad7f6ec69a02
Revises: 2842a5a82592
Create Date: 2026-06-03 11:43:32.137354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad7f6ec69a02'
down_revision: Union[str, Sequence[str], None] = '2842a5a82592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refreshtokens', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('refreshtokens', sa.Column('user_agent', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refreshtokens', 'user_agent')
    op.drop_column('refreshtokens', 'ip_address')
    # ### end Alembic commands ###
