"""add mobile device fields to refreshtokens

Revision ID: edf73efecea0
Revises: ad7f6ec69a02
Create Date: 2026-06-03 11:59:29.537851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edf73efecea0'
down_revision: Union[str, Sequence[str], None] = 'ad7f6ec69a02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refreshtokens', sa.Column('device_id', sa.String(length=255), nullable=True))
    op.add_column('refreshtokens', sa.Column('device_name', sa.String(length=255), nullable=True))
    op.add_column('refreshtokens', sa.Column('platform', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refreshtokens', 'platform')
    op.drop_column('refreshtokens', 'device_name')
    op.drop_column('refreshtokens', 'device_id')
    # ### end Alembic commands ###
