FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

FROM node:20-alpine

WORKDIR /app

RUN npm install -g http-server

COPY --from=builder /app/dist ./dist
COPY package*.json ./

EXPOSE 3000

CMD ["http-server", "dist", "-p", "3000", "-c-1"]
