services:
  srv_db:
    image: postgres:15
    container_name: ctr_postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-fastapi_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backendnetwork
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-fastapi_db}" ]
      interval: 5s
      timeout: 5s
      retries: 5
  
  srv_mongodb:
    image: mongo:8
    container_name: ctr_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-admin123}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-inventory_db}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backendnetwork
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  srv_redis:
    image: redis:alpine
    container_name: ctr_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backendnetwork
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  srv_auth:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    container_name: ctr_auth
    depends_on:
      srv_db:
        condition: service_healthy
      srv_redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file:
      - ./AuthService/.env
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@srv_db:5432/${POSTGRES_DB:-fastapi_db}
      REDIS_URL: redis://srv_redis:6379/0
    volumes:
      - ./AuthService:/app
    restart: always
    networks:
      - backendnetwork

  srv_inventory:
    build:
      context: ./InventoryService
      dockerfile: Dockerfile
    container_name: ctr_inventory
    depends_on:
      srv_db:
        condition: service_healthy
      srv_redis:
        condition: service_healthy
    ports:
      - "8001:3000"
    env_file:
      - ./InventoryService/.env
    environment:
      MONGODB_URI: mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-admin123}@srv_mongodb:27017/${MONGO_DATABASE:-inventory_db}?authSource=admin
      REDIS_URL: redis://srv_redis:6379/0
      TSC_WATCHFILE: PriorityPollingInterval
    volumes:
      - ./InventoryService:/app
      - /app/node_modules
    restart: always
    networks:
      - backendnetwork

  srv_pgadmin:
    image: dpage/pgadmin4
    container_name: ctr_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "5050:80"
    depends_on:
      - srv_db
    networks:
      - backendnetwork

  srv_dbgate:
    image: dbgate/dbgate
    container_name: ctr_dbgate
    restart: always
    ports:
      - "5051:3000"
    volumes:
      - dbgate_data:/root/.dbgate
    networks:
      - backendnetwork

volumes:
  postgres_data:
  mongodb_data:
  dbgate_data:

networks:
  backendnetwork:
    driver: bridge
