x-postgres-port: &postgres-port 5432
x-postgres-port-map: &postgres-port-map "5432-5442"
x-common-env: &common-env
  DEBUG: True
  ENVIRONMENT: development
  SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
  JWT_SECRET: 882e566736203115c544837549b67484d85202860d5b630f784f1837d3897850
  ALGORITHM: HS256
  ACCESS_TOKEN_EXPIRE_MINUTES: 30
  REFRESH_TOKEN_EXPIRE_DAYS: 7

  # Database
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: postgres
  POSTGRES_PORT: *postgres-port

  MONGODB_URI: mongodb://admin:admin123@srv_mongodb:27017/inventory_db?authSource=admin
  REDIS_URL: redis://srv_redis:6379/0

x-common-service: &common-service
  restart: always
  networks:
    - backendnetwork

services:
  srv_opensearch:
    <<: *common-service
    image: opensearchproject/opensearch:2.19.1
    container_name: ctr_opensearch
    restart: unless-stopped
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node
      - discovery.type=single-node

      # Disable demo security (Development only)
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - DISABLE_SECURITY_PLUGIN=true

      # memory lock
      - bootstrap.memory_lock=true

      # Java Heap
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m

      # Disable mmap
      - node.store.allow_mmap=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1" ]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 30s
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"

  srv_os_dashboards:
    <<: *common-service
    image: opensearchproject/opensearch-dashboards:2.19.1
    container_name: ctr_os_dashboards
    restart: unless-stopped
    environment:
      OPENSEARCH_HOSTS: '["http://srv_opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
    ports:
      - "5601:5601"
    depends_on:
      srv_opensearch:
        condition: service_healthy

  srv_postgres_db:
    <<: *common-service
    image: postgres:15-alpine
    container_name: ctr_postgres_db
    environment:
      <<: *common-env
    ports:
      - *postgres-port-map
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  srv_mongodb:
    <<: *common-service
    image: mongo:8
    container_name: ctr_mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_INITDB_DATABASE=inventory_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  srv_redis:
    <<: *common-service
    image: redis:alpine
    container_name: ctr_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  srv_pgadmin:
    <<: *common-service
    image: dpage/pgadmin4
    container_name: ctr_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - srv_postgres_db

  srv_dbgate:
    <<: *common-service
    image: dbgate/dbgate
    container_name: ctr_dbgate
    ports:
      - "5051:3000"
    volumes:
      - dbgate_data:/root/.dbgate

  srv_auth:
    <<: *common-service
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    container_name: ctr_auth
    depends_on:
      srv_postgres_db:
        condition: service_healthy
      srv_redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file:
      - ./AuthService/.env
    environment:
      <<: *common-env
      POSTGRES_DB: fastapi_db
    volumes:
      - ./AuthService:/app

  srv_inventory:
    <<: *common-service
    build:
      context: ./InventoryService
      dockerfile: Dockerfile
    container_name: ctr_inventory
    depends_on:
      srv_postgres_db:
        condition: service_healthy
      srv_redis:
        condition: service_healthy
    ports:
      - "8001:3000"
    env_file:
      - ./InventoryService/.env
    environment:
      <<: *common-env
      OPENSEARCH_URL: http://srv_opensearch:9200
      TSC_WATCHFILE: PriorityPollingInterval
    volumes:
      - ./InventoryService:/app
      - inventory_node_modules:/app/node_modules

  srv_order:
    <<: *common-service
    build:
      context: ./OrderService
      dockerfile: Dockerfile.dev
    container_name: ctr_order
    depends_on:
      srv_postgres_db:
        condition: service_healthy
    ports:
      - "8002:3000"
      - "5555:5555"
    env_file:
      - ./OrderService/.env.development
    environment:
      <<: *common-env
      POSTGRES_DB_HOST: srv_postgres_db
      POSTGRES_DB_NAME: order_db
      DATABASE_URL: postgresql://postgres:postgres@srv_postgres_db:5432/order_db
    volumes:
      - ./OrderService:/app
      - order_node_modules:/app/node_modules

  srv_ocr:
    <<: *common-service
    build:
      context: ./OcrService
      dockerfile: Dockerfile
    container_name: ctr_ocr
    depends_on:
      srv_opensearch:
        condition: service_healthy
      srv_mongodb:
        condition: service_healthy
      srv_redis:
        condition: service_healthy
    ports:
      - "8003:3000"
    env_file:
      - ./OcrService/.env
    environment:
      <<: *common-env
      OPENSEARCH_URL: http://srv_opensearch:9200
      MONGODB_URI: mongodb://admin:admin123@srv_mongodb:27017/ocr_db?authSource=admin
      TSC_WATCHFILE: PriorityPollingInterval
    volumes:
      - ./OcrService:/app
      - ocr_node_modules:/app/node_modules

  srv_tools:
    <<: *common-service
    build:
      context: ./ToolsService
      dockerfile: Dockerfile
    container_name: ctr_tools
    depends_on:
      srv_postgres_db:
        condition: service_healthy
      srv_redis:
        condition: service_healthy
    ports:
      - "8004:8000"
    env_file:
      - ./ToolsService/.env
    environment:
      <<: *common-env
<<<<<<< HEAD
      OPENAI_API_KEY: YOUR_OPENAI_API_KEY
=======
>>>>>>> 1e9f4b3 (added tools service)
      POSTGRES_DB: fastapi_db
    volumes:
      - ./ToolsService:/app

volumes:
  opensearch_data:
  postgres_data:
  mongodb_data:
  dbgate_data:
  inventory_node_modules:
  order_node_modules:
  ocr_node_modules:

networks:
  backendnetwork:
    driver: bridge
