FROM node:22-alpine AS development

#working directory inside the container
WORKDIR /app

#copy package.json and package-lock.json file into the app
COPY package*.json ./

#Install depencies
RUN npm ci

#Copy rest project files
COPY . .

#Run dev command accoring to package.json
CMD ["npm", "run", "start:dev"]