"""add request_id to audit logs

Revision ID: dee28e8b3cc1
Revises: 1d6cebd13b2f
Create Date: 2026-06-04 12:36:57.785308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dee28e8b3cc1'
down_revision: Union[str, Sequence[str], None] = '1d6cebd13b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('request_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'request_id')
    # ### end Alembic commands ###
